### ISSUE TITLE
Name of binary doesn't match name of repo

### ISSUE THREAD

**Issue by jpfairbanks** [rjhorniii/ical2org#11]
You want the binary to be `ical2org` but the repo is called `ical2org-go` which conflicts with what `go install` expects. 

You can:

1. rename the repo to ical2org
2. tell the user to build and install in two steps
3. put the main program in a subdirectory like `rjhornii/ical2org-go/ical2org/main.go`

I like 1 and 3

**Comment by rjhorniii** [comment]
I'll go with #1.  It looks more like the general style.

(Is there a page somewhere that I could read and link to that covers this kind of expectation?  Stumbling around, making mistakes, and learning is fun for the audience but a bit of  a waste of time.)

**Comment by rjhorniii** [comment]
Revised instructions to match and renamed repository.  https://github.com/rjhorniii/ical2org/commit/90e180f36ea85c66f68525bade33e80d59298465#diff-04c6e90faac2675aa89e2176d2eec7d8
