### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by floli** [rjhorniii/ical2org#7]
As a Go non-user I wonder how to build the package?

Some build instruction or even a build script would be great!

**Comment by rjhorniii** [comment]
I hesitate to describe how to install or set up go.  My experience is with Linux, where you can usually just install the package or packages.   If you are a real novice, borrow or buy "The Go Programming Language", by Alan Donovan and Brian Kernighan.  Chapter 10 describes the usual directory structures and commands for using go, particularly section 10.7.

A default installation would then allow the commands:

go get github.com/rjhorniii/ics-golang
go get github.com/rjhorniii/ical2org-go
cd where-you-want-the-executable
go build github.com/rjhorniii/ical2org

This will result in an executable ical2org in that directory.

There are lots of other possible variations.
